[package]
name = "pwd"
version = "0.1.0"
edition = "2021"
author = "Mido Akeel"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
